version: '3.3'

services:
  challenge:
    build: challenge
    entrypoint: /bin/true

  ctfd:
    container_name: ctfd
    build: CTFd
    user: root
    restart: always
    privileged: true
    ulimits:
        nofile:
            soft: 32768
            hard: 1048576
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=8
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SERVER_SENT_EVENTS=false
    env_file:
      - ./data/config.env
    volumes:
      - ./data:/var/data
      - ./data/CTFd/logs:/var/log/CTFd
      - ./data/CTFd/uploads:/var/uploads
      - ./data/homes:/var/homes:shared
      - ./data/challenges:/var/challenges
      - ./CTFd:/opt/CTFd:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - db

  db:
    container_name: ctfd_db
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./data/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    container_name: ctfd_cache
    image: redis:4
    restart: always
    volumes:
      - ./data/redis:/data

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: ctfd_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOCKER_HOST=unix:///tmp/${DOCKER_PSLR}/docker.sock
    volumes:
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - ./nginx-proxy/etc/nginx/conf.d/pwncollege.conf:/etc/nginx/conf.d/pwncollege.conf
      - ./nginx-proxy/etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/etc/passwd:/etc/passwd
      - ./data/homes:/var/homes:shared
      - /var/run/docker.sock:/tmp/${DOCKER_PSLR}/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: ctfd_acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  html:
  dhparam:
  certs:
  acme:
